#!/usr/bin/env php

<?php
  echo "Content-Type: text/html\r\n";
  echo "\r\n";

  echo "<!doctype html>";
  echo "<html>";
  echo "<body>";
  echo "<h1>Hello from PHP CGI</h1>";
  echo "<p>This page was generated by PHP.</p>";
  echo "</body>";
  echo "</html>";
  ?>
