# testkommentar



# testkommentar
			 

     # testkommentar

server {
    # listen 80;
	listen 127.0.0.1:80;
    server_name localhost;
	is_default_server false;

    root /usr/share/nginx/html;
    index index.html;

    # location / {
    #     try_files $uri $uri/ =404;
    # }
}
