# testkommentar



# testkommentar
			 

     # testkommentar

server {
    listen 8080;
	listen 0.0.0.0:8080;
    server_name localhost;
	is_default_server false;

    error_page 400 /errors/400.html;
    error_page 400 /errors/400.htmlaaa;
    error_page 403 /errors/403.html;

	root /usr/share/nginx/html;
    index index.html;

    location /root {
        index           index.html;
        methods         GET POST;
        autoindex       off;
		return          302 http://localhost:8080/;
		upload_store    ./uploads/admin;
		cgi_ext         .py /usr/bin/python3;
    }

    location /abc {
        index           index.html;
		root			/herbert;
        methods         GET POST;
        autoindex       off;
		return          302 http://localhost:8080/;
		upload_store    ./uploads/admin;
		cgi_ext         .py /usr/bin/python3;
    }

    location /def {
        index           index.html;
        methods         GET POST;
        autoindex       off;
		return          302 http://localhost:8080/;
		upload_store    ./uploads/admin;
		cgi_ext         .py /usr/bin/python3;
    }

}
