#https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
#nginx: [emerg] invalid value "asdf" in "autoindex" directive, it must be "on" or "off" in /etc/nginx/http.d/vhost.conf:10
http {
	client_header_buffer_size 1k;
   	client_timeout 50s;
	client_max_body_size 50M;

	server {
		listen 0.0.0.0:8081;
		# server_name anders;
		autoindex off;
		root ./html/static;
		index index.html;
		location / {
		allow_methods GET POST DELETE;
		}
	}

	server {
		listen 0.0.0.0:8081;
		server_name example.com;
		autoindex off;
		root ./html/static;
		index static_index.html;
		location / {
		allow_methods GET POST DELETE;
		}
    }

	server {
		listen 8082;
		autoindex on;
		root ./html/directory;
		location /
		{
			autoindex on;
		}
		location /wrong/url {
    		return 444;
		}
		location /permanently/moved/url {
			return 301 http://www.example.com/moved/here;
		}
    }

	server {
		client_header_buffer_size 1k;
	   	client_timeout 60s;
		client_max_body_size 1M;

		listen 0.0.0.0:8083;
		autoindex on;
		root ./html/;
		location /upload/ {
			root ./html/upload_files;
        	upload_store /;
			allow_methods GET POST DELETE;
    	}
		location /errors/ {
			error_page 404 501     /error.html;
			error_page 502     /error502.html;
		}
    }

	server {
		listen 127.0.0.1:8084;
		server_name localhost;
		autoindex off;
		root ./html/static;
		index /index.html;

		location /cgi-php/ {
			cgi_path /usr/bin/php-cgi;
			root ./html/cgi_files/php;
			cgi_ext .php;
			index index.php;
		}
	}

	server {
		listen 127.0.0.1:8085;
		server_name localhost;
		autoindex off;
		root ./html/static;
		index /index.html;

		location /cgi-py/ {
			cgi_path /usr/bin/python3;
			cgi_ext .py;
			root ./html/cgi_files/py;
			index /test.py;
		}
	}

	server {
		listen 0.0.0.0:8086;
		autoindex on;
		root ./html/static;
		index index.html;
		location /
		{
			allow_methods ; # block all methods
		}
    }

	server {
		listen 8087;
		server_name example.com beispiel.com;
		root /;
		index README.md;
	}

}
