server {
    listen 8081;
    server_name vogel;

	root ./grillserv;
    index index.html;

    error_page 404 /www/errors/404.html;

    # location / {
    #     index           index.html;
    #     methods         GET POST;
    #     autoindex       off;
    # }

    location /maus {
		root			./grillserv;
        index           index.html;
        methods         GET POST;
        autoindex       off;
    }

    location /vogel {
		root			./grillserv;
        index           index.html;
        methods         GET POST;
        autoindex       off;
    }

    location /hund {
		root			./futter;
        index           index.html;
        methods         GET POST;
        autoindex       off;
    }
}
