server {
    listen 8081;
    server_name vogel;

	root ./grillserv;
    # index index.html;

    error_page 404 /www/errors/404.html;

    location / {
         index           index.html;
         methods         GET POST;
        # autoindex       on;
    }

	location /script/ {
      root     ./html/cgi_py;
      cgi_ext  .py /usr/bin/python3;
  	}
}
