server {
    listen 8081;
    server_name vogel;

	root ./bbqserv;
    index index.html;

    error_page 404 /www/errors/404.html;
	client_max_body_size 0;

    location / {
        index           index.html;
        methods         GET;
        autoindex       on;
    }
}
