# ─────────────────────────────────────────
#  Server 1 – Main-Testserver (port 8080)
# ─────────────────────────────────────────
server {
    listen             		8080;
    server_name         	apple;
    is_default_server   	true;
    client_max_body_size 	1m;

    root                ./bbqserv;

    error_page 404 /bbqserv/errors/404.html;

    # root location - index.html, GET only
    location / {
        index           index.html;
        methods         GET;
        autoindex       off;
        upload          off;
    }

    # static files - GET only, no autoindex
    location /static {
        methods         GET;
        autoindex       off;
    }

    # autoindex
    location /autoindex_dir {
        methods         GET;
        autoindex       on;
    }

    # cgi
    location /cgi {
        methods         GET POST;
        autoindex       on;
        cgi_ext         .py /usr/bin/python3;
        cgi_ext         .php /usr/bin/php-cgi;
    }

    # redirect
    location /redirect-test {
        return          301 /static/hello.txt;
    }
}

server {
    listen 8080;
    server_name cherry;

	root ./bbqserv;
    index index.html;

    error_page 404 /www/errors/404.html;
	client_max_body_size 0;

    location / {
        index           index.html;
        methods         GET;
        autoindex       on;
    }

	location /upload {
		methods			GET POST;
		upload			on;
	}
}

server {
    listen 8081;
    server_name banana;

	root ./bbqserv;
    index index.html;

    error_page 404 /www/errors/404.html;
	client_max_body_size 0;

    location / {
        index           index.html;
        methods         GET;
        autoindex       on;
    }
}