server {
    listen 8081;
    server_name maus;

	root ./danceserv;
    # index index.html;

    error_page 404 /www/errors/404.html;

     location / {
         index           index.html;
         methods         GET POST;
        # autoindex       on;
     }

    location /vogel {
		root			./danceserv;
        index           index.html;
        methods         GET POST;
        autoindex       off;
    }

   
    location /auto {
        root            ./danceserv;
        index           index.html;
        methods         GET POST DELETE;
    	# upload_store    ./uploads/tests/;
		upload			on;
        autoindex       on;
    }

    location /maus {
        #alias           ./futter
		root			./danceserv;
        index           index.html;
        methods         GET POST;
        # upload_store    uploads;
		upload			off;
        autoindex       off;
    }



    location /hund {
		root			./futter;
        index           index.html;
        methods         GET POST;
        autoindex       off;
    }
}
